### ISSUE TITLE
My whole !@#$ system broke!

### ISSUE THREAD

**Issue by tisz0501** [kristovatlas/osx-config-check#186]
This is some piece of malware. After running this audit and "accept" to change my settings the system keeps those fucking settings. Now, when I want to manually change a setting it automatically goes back because of this shit script. Pull this script offline. You are breaking people's systems!

**Comment by tisz0501** [comment]
Fuck you piece of shit

**Comment by kristovatlas** [comment]
Feel free to open another issue if you think you can report the details of what went wrong like an adult.
