### ISSUE TITLE
config false positive: git is up to date or not installed

### ISSUE THREAD

**Issue by kristovatlas** [kristovatlas/osx-config-check#73]
A user reported that this test failed repeatedly after disabling it.

**Comment by hypn** [comment]
On El Capitan it's not possible to move "git", "openssl" or "curl" without booting in to Recovery mode - more info on https://ohthehugemanatee.org/blog/2015/10/01/how-i-got-el-capitain-working-with-my-developer-tools/

So the current "fix" doesn't work. Perhaps checking "which git" and ensuring the non-default is not returned is a sufficient check?

**Comment by kristovatlas** [comment]
@hypn dang, that's inconvenient. Thanks for the info.

The goal for this check is to make sure that, when the user runs "git" from Terminal, they run an up-to-date version of it. Aside from renaming apple's git, it seems the only other way to ensure that homebrew's git installation is prioritized is to move brew installations (`/usr/local/...`) earlier in the PATH environment variable than `/usr/bin/`, but that seems difficult to do programmatically.

Reference: http://apple.stackexchange.com/questions/93002/how-to-properly-update-git-on-mac#93179

**Comment by kristovatlas** [comment]
To do this programmatically, we can target a file that holds paths information and use this `sed` template to do the insertion (with sudo privs if necessary, depending on the file we target):

http://unix.stackexchange.com/questions/121161/how-to-insert-text-after-a-certain-string-in-a-file#121173

Files to choose from (Reference: http://superuser.com/questions/69130/where-does-path-get-set-in-os-x-10-6-snow-leopard ):
 * `/etc/profile`
 * `~/.bash_profile`
 * `~/.bash_login`   (if .bash_profile does not exist)
 * `~/.profile`      (if .bash_login does not exist)
 * `/etc/paths`
 * `/etc/paths.d`

I'm not clear on how precedence works for this yet. All `/etc/*` locations would require sudo privs and impact all users.

**Comment by kristovatlas** [comment]
http://apple.stackexchange.com/questions/93002/how-to-properly-update-git-on-mac#93179

adding 
`export PATH="/usr/local/bin:$PATH"`
to the end of  `~/.bash_profile`

might do the trick, but we should verify first that /usr/local/bin path is not already in a good spot via regex and remove all instances of it in bad spots before prepending it to PATH. Also, need to make sure that this will not require a reboot in order to take effect for the user.
