### ISSUE TITLE
Report Mode

### ISSUE THREAD

**Issue by bs071** [kristovatlas/osx-config-check#82]
Feature Request
Run with out interactive prompts on client machines in order to get a high-level report of all the pass/fails.

**Comment by kristovatlas** [comment]
I like this idea. How would you prefer this to be enabled? A command-line argument, such as `app.py --report-only`?

**Comment by kristovatlas** [comment]
ping @bs071

**Comment by bs071** [comment]
@kristovatlas, yes, command-line arg would be awesome.

Thanks!

**Comment by kristovatlas** [comment]
Satisfied in the above reference PR
