### ISSUE TITLE
bug: shebang missing

### ISSUE THREAD

**Issue by kristovatlas** [kristovatlas/osx-config-check#84]
Reddit user Krezil [noted](https://www.reddit.com/r/netsec/comments/4sido1/github_kristovatlasosxconfigcheck_verify_the/d5ad8yd) that the shebang character sequence is missing from bash scripts.

**Comment by kristovatlas** [comment]
https://en.wikipedia.org/wiki/Shebang_(Unix)

**Comment by ministrike3** [comment]
Is the solution to this literally to add add shebangs to several bash scripts that he notes are missing them? Cause if so I'm down to do it

**Comment by kristovatlas** [comment]
Yes, I think so. Thanks for offering to help, @ministrike3

**Comment by kristovatlas** [comment]
Added to app.py.

**Comment by kristovatlas** [comment]
Shebang is in app.py and various .sh scripts, so I think this is good enough for now.
