### ISSUE TITLE
Remove Enum Requirement

### ISSUE THREAD

**Issue by Cabalist** [kristovatlas/osx-config-check#91]
Looking over the usage of Enum in this project it doesn't look like the library is necessary.  How would changing `Enum` to `object` in the code change functionality?

```python
class Confidence(object):
    """Likelihood that a configuration will create negative side-effects.

    A lower integer value indicates less likelihood that a configuration will
    cause problems with applications.
    """
    required = 1
    recommended = 2
    experimental = 3
```

I believe the extra bits that the `Enum` library provides are for iteration and type comparison which are not used.

**Comment by kristovatlas** [comment]
You were quite correct. Thanks for helping me clean up the code!
